#ifndef CONSTANTS_H
#define CONSTANTS_H
#include <limits.h>

// STRINGS
#define PROMPT %%
#define COMMAND_MAX_LENGTH 200
#define COMMAND_MAX_ARGUMENTS 100

// FILE NAME
#define FILE_NAME_MAX_SIZE 100
#define FILE_PATH_MAX_SIZE PATH_MAX

#define DEBUG 0

// EXECUTE STATUS RESULT
#endif