#ifndef CONSTANTS_H
#define CONSTANTS_H

// STRINGS
#define PROMPT %%
#define COMMAND_MAX_LENGTH 200
#define COMMAND_MAX_ARGUMENTS 100

// FILE NAME
#define FILE_NAME_MAX_SIZE 100
#define FILE_NAME_MAX_SIZE 100

#define DEBUG 1

// EXECUTE STATUS RESULT
#endif